server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  user: root
  password: "your-password"
  dbname: homework_system

jwt:
  secret: "your-key"
  access_expire: 30
  refresh_expire: 10080